### ISSUE TITLE
Add missing `index.js` to published package.

### ISSUE THREAD

**Issue by izaakschroeder** [jfmengels/eslint-plugin-lodash-fp#12]
Since this also causes the package not to work. 😄

**Comment by jfmengels** [comment]
It's in there, but I think I probably published it with the `npm` version included in Node v6. And that one has problems where it does not publish all the files in the package...
Will re-publish when I have a more stable connexion.
Thanks for reporting it!

**Comment by jfmengels** [comment]
Published `1.1.0`, and `1.1.1` right after because I published it with node v6 again...
Anyway, sorry about the mess, hopefully it won't happen again, and I hope you'll like the plugin :)
Thanks for the reports!
