### ISSUE TITLE
Importing placeholder alone

### ISSUE THREAD

**Issue by Andarist** [jfmengels/eslint-plugin-lodash-fp#40]
Hey, I'm scattering through the docs and source code, but cant find if there is a way in `lodash/fp` to import just that except smth like:
`import { placeholder as _ } from 'lodash/fp/curry'`

which unfortunately is against `no-submodule-destructuring`. Using module bundler I do not want to import whole `lodash/fp` just to access placeholder.

**Comment by jfmengels** [comment]
Currently the only way I see is to do the following
```js
const {placeholder as _} = require('lodash/fp');

// I tried this but that does not seem to work
const _ = require('lodash/fp/placeholder');
```

The second option is to disable the `no-submodule-destructuring` rule for that line, which is an acceptable tradeoff IMO (especially if you comment why).

The [Lodash Gitter chat](https://gitter.im/lodash/lodash) is perfect for questions like these :)
In this case, you can probably open an issue on Lodash to try to get `placeholder` through `lodash/fp/placeholder`, as that should work IMO.
