### ISSUE TITLE
`lodash-fp/use-fp` is incorrectly triggered for module names that start with "lodash-"

### ISSUE THREAD

**Issue by penny-five** [jfmengels/eslint-plugin-lodash-fp#41]
For example the following require call causes an error even when it shouldn't:
> const LodashWebpackPlugin = require('lodash-webpack-plugin');

**Comment by jfmengels** [comment]
Thanks for reporting @penny-five!

I published a fix in v2.1.0. Let me know if it doesn't work well for you.
