### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by robwise** [jfmengels/eslint-plugin-lodash-fp#56]
I don't see any activity on here? I'd be willing to help out with this if you want.

**Comment by graingert** [comment]
@jfmengels is still alive, (committing in various places)

**Comment by graingert** [comment]
@jfmengels ping

**Comment by jdalton** [comment]
Looks like the repo could use some volunteers to tackle some of this and some of that. @graingert would you be up for it?

**Comment by graingert** [comment]
I can definitely help out

**Comment by nickmccurdy** [comment]
I may be able to help out if you can list some high priority issues/refactors or set up a roadmap.

**Comment by graingert** [comment]
@robwise this project is dead no more!

**Comment by jdalton** [comment]
Awesome @graingert! 

Thank you!
